services:
  backend:
    build: ./server
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  frontend:
    build: ./client
    ports:
      - "4200:4200"
    depends_on:
      - backend

  mongo:
    image: mongo:6
    restart: always
    environment:
      MONGO_INITDB_DATABASE: worldquiz
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    depends_on:
      - mongo

volumes:
  mongo_data:
