version: '3.8'

services:
  backend:
    build: ./server
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    depends_on:
      - database

  frontend:
    build: ./client
    ports:
      - "4200:4200"
    depends_on:
      - backend

  database:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: